dist: trusty
sudo: require

language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - $CC $(find *.c | grep -v "tcl*" | grep -v "pcap*" | grep -v "openssl*")
